
USE master;
GO

-- Drop and recreate the 'DataWarehouseAnalytics' database
IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'DataWarehouseAnalytics')
BEGIN
    ALTER DATABASE DataWarehouseAnalytics SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE DataWarehouseAnalytics;
END;
GO

-- Create the 'DataWarehouseAnalytics' database
CREATE DATABASE DataWarehouseAnalytics;
GO

USE DataWarehouseAnalytics;
GO

-- Create Schemas

CREATE SCHEMA gold;
GO

CREATE TABLE gold.dim_customers(
	customer_key int,
	customer_id int,
	customer_number nvarchar(50),
	first_name nvarchar(50),
	last_name nvarchar(50),
	country nvarchar(50),
	marital_status nvarchar(50),
	gender nvarchar(50),
	birthdate date,
	create_date date
);
GO

CREATE TABLE gold.dim_products(
	product_key int ,
	product_id int ,
	product_number nvarchar(50) ,
	product_name nvarchar(50) ,
	category_id nvarchar(50) ,
	category nvarchar(50) ,
	subcategory nvarchar(50) ,
	maintenance nvarchar(50) ,
	cost int,
	product_line nvarchar(50),
	start_date date 
);
GO

CREATE TABLE gold.fact_sales(
	order_number nvarchar(50),
	product_key int,
	customer_key int,
	order_date date,
	shipping_date date,
	due_date date,
	sales_amount int,
	quantity tinyint,
	price int 
);
GO

TRUNCATE TABLE gold.dim_customers;
GO

BULK INSERT gold.dim_customers
FROM 'path/to/csv_files\gold.dim_customers.csv'
WITH (
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	TABLOCK	
);
GO

TRUNCATE TABLE gold.dim_products;
GO

BULK INSERT gold.dim_products
FROM 'path/to/csv_files\gold.dim_products.csv'
WITH (
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	TABLOCK
);
GO

TRUNCATE TABLE gold.fact_sales;
GO

BULK INSERT gold.fact_sales
FROM 'path/to/csv_files\gold.fact_sales.csv'
WITH (
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	TABLOCK
);
GO




------------------ DB explorations --------------------------

SELECT * FROM INFORMATION_SCHEMA.tables;


SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'


------------------- Dim Explorations -----------------------

SELECT DISTINCT Country FROM gold.dim_customers;

SELECT DISTINCT category , subcategory , product_name 
FROM gold.dim_products
ORDER BY 1,2,3;


------------------- Date Exploration -----------------------

SELECT 
MIN(order_date) AS first_order_date,
MAX(order_date) AS last_order_date,
DATEDIFF(year , MIN(order_date), MAX(order_date)) AS years_range
FROM gold.fact_sales;


-- Find date of youngest and oldest customer.

SELECT 
MIN(birthdate) AS oldest_birthdate,
DATEDIFF(year ,MIN(birthdate) , GETDATE()) AS age_of_oldest_customer,
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(year , MAX(birthdate) ,GETDATE()) AS age_of_youngest_customer
FROM gold.dim_customers

---------------------- Measure Explorations --------------------------

-- Find total Sales

SELECT SUM(sales_amount) AS Total_sales
FROM gold.fact_sales;

-- Find how many items sold
SELECT SUM(quantity) AS qty_sold
FROM gold.fact_sales;

-- AVG Price

SELECT AVG(price) AS avg_price 
FROM gold.fact_sales;

-- Total Orders
SELECT COUNT(DISTINCT order_number) AS Total_orders
FROM gold.fact_sales;

-- Total Products 

SELECT COUNT(DISTINCT product_key) AS Total_products
FROM gold.dim_products;

-- Total Customers

SELECT COUNT(customer_key) FROM gold.dim_customers;

-- Find customers that have placed an order.

SELECT COUNT(DISTINCT customer_key) FROM gold.dim_customers;

-- Generate a report of all key metrics of our business.


SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity)  FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price)  FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders',COUNT(DISTINCT order_number)  FROM gold.fact_sales
UNION ALL
SELECT 'Total Products',COUNT(DISTINCT product_key) FROM gold.dim_products
UNION ALL
SELECT 'Total Customers',COUNT(DISTINCT customer_key) FROM gold.dim_customers


----------------------- Magnitude Exploration -----------------------

-- Total Customers by Country

SELECT Country,
	   COUNT(customer_key) AS Total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY Total_customers DESC;

-- Total Customers by Gender

SELECT Gender, COUNT(customer_key) AS Total_Customers 
FROM gold.dim_customers
GROUP BY Gender;

-- Total Products BY Category

SELECT category , 
COUNT(product_key) Total_Products
FROM gold.dim_products
GROUP BY category
ORDER BY category DESC;


-- AVG cost in each category

SELECT category,
	   AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;

-- Total Revenue generated by each category

SELECT dc.category , SUM(fc.quantity * fc.price) AS Total_Revenue 
FROM gold.dim_products dc
INNER JOIN gold.fact_sales fc
	ON dc.product_key = fc.product_key
GROUP  BY dc.category;


SELECT dp.category , SUM(fc.sales_amount) AS Total_Revenue 
FROM gold.fact_sales fc
LEFT JOIN gold.dim_products dp
	ON dp.product_key = fc.product_key
GROUP  BY dp.category
ORDER BY Total_Revenue DESC;


-- What is Total Revenue by each customer

SELECT * FROM gold.dim_customers;
SELECT * FROM gold.fact_sales;


SELECT c.customer_key,
	   CONCAT(c.first_name , ' ' , c.last_name) AS customer_name,
	   SUM(f.sales_amount) AS Total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
	ON f.customer_key = c.customer_key
GROUP BY c.customer_key , c.first_name , c.last_name
ORDER BY Total_revenue DESC;



-- Distribution of sold items by countries.


SELECT c.country,
	   SUM(f.quantity) AS total_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
	ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold DESC;


--------------------------- Ranking ------------------------

-- 5 products generated the highest revenue.

SELECT
	TOP 5
	dp.product_name , 
	SUM(fc.sales_amount) AS Total_Revenue 
FROM gold.fact_sales fc
LEFT JOIN gold.dim_products dp
	ON dp.product_key = fc.product_key
GROUP  BY dp.product_name
ORDER BY Total_Revenue DESC;


-- 5 Worst Performing Products 

SELECT
	TOP 5
	dp.product_name , 
	SUM(fc.sales_amount) AS Total_Revenue 
FROM gold.fact_sales fc
LEFT JOIN gold.dim_products dp
	ON dp.product_key = fc.product_key
GROUP  BY dp.product_name
ORDER BY Total_Revenue;

SELECT * 
FROM
	(SELECT 
		--TOP 5
		p.product_name,
		SUM(f.sales_amount) AS total_sales,
		ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) as rank_products
		FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
		ON p.product_key = f.product_key
	GROUP BY p.product_name
) t
WHERE rank_products <=5;


-- Top 10 customers who have generated the highest revenue.

SELECT f.customer_key,
	   c.first_name,
	   c.last_name,
	   SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
	ON f.customer_key = c.customer_key
GROUP BY f.customer_key , c.first_name, c.last_name
ORDER BY total_revenue DESC;


-- Top 3 Customers with Fewest orders placed.


SELECT * FROM gold.dim_customers;

SELECT * FROM gold.fact_sales;

SELECT * FROM gold.dim_products;


SELECT 
	TOP 3
	c.customer_key,
	c.first_name,
	c.last_name,
	COUNT(DISTINCT f.order_number) AS total_orders_placed
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
	ON f.customer_key = c.customer_key
GROUP BY c.customer_key,
		 c.first_name,
		 c.last_name
ORDER BY total_orders_placed;
